const ActionTypes = {
  FETCH_QUESTIONNAIRES_START: 'FETCH_QUESTIONNAIRES_START',
  FETCH_QUESTIONNAIRES_SUCCESS: 'FETCH_QUESTIONNAIRES_SUCCESS',
  FETCH_QUESTIONNAIRES_FAILURE: 'FETCH_QUESTIONNAIRES_FAILURE',
  CREATE_QUESTIONNAIRE_START: 'CREATE_QUESTIONNAIRE_START',
  CREATE_QUESTIONNAIRE_SUCCESS: 'CREATE_QUESTIONNAIRE_SUCCESS',
  CREATE_QUESTIONNAIRE_FAILURE: 'CREATE_QUESTIONNAIRE_FAILURE',
};

export default ActionTypes;

