const ActionTypes = {
  FETCH_QUESTIONNAIRES_START: 'FETCH_QUESTIONNAIRES_START',
  FETCH_QUESTIONNAIRES_SUCCESS: 'FETCH_QUESTIONNAIRES_SUCCESS',
  FETCH_QUESTIONNAIRES_FAILURE: 'FETCH_QUESTIONNAIRES_FAILURE',
  FETCH_QUESTIONNAIRE_START: 'FETCH_QUESTIONNAIRE_START',
  FETCH_QUESTIONNAIRE_SUCCESS: 'FETCH_QUESTIONNAIRE_SUCCESS',
  FETCH_QUESTIONNAIRE_FAILURE: 'FETCH_QUESTIONNAIRE_FAILURE',
  CREATE_QUESTIONNAIRE_START: 'CREATE_QUESTIONNAIRE_START',
  CREATE_QUESTIONNAIRE_SUCCESS: 'CREATE_QUESTIONNAIRE_SUCCESS',
  CREATE_QUESTIONNAIRE_FAILURE: 'CREATE_QUESTIONNAIRE_FAILURE',
  DELETE_QUESTIONNAIRE_START: 'DELETE_QUESTIONNAIRE_START',
  DELETE_QUESTIONNAIRE_SUCCESS: 'DELETE_QUESTIONNAIRE_SUCCESS',
  DELETE_QUESTIONNAIRE_FAILURE: 'DELETE_QUESTIONNAIRE_FAILURE',
  CREATE_QUESTION_START: 'CREATE_QUESTION_START',
  CREATE_QUESTION_SUCCESS: 'CREATE_QUESTION_SUCCESS',
  CREATE_QUESTION_FAILURE: 'CREATE_QUESTION_FAILURE',
  REMOVE_ACTIVEQUESTIONNAIRE: 'REMOVE_ACTIVEQUESTIONNAIRE',
};

export default ActionTypes;

