const ActionTypes = {
  ACTIVATE_POLL_START: 'ACTIVATE_POLL_START',
  ACTIVATE_POLL_SUCCESS: 'ACTIVATE_POLL_SUCCESS',
  ACTIVATE_POLL_FAILURE: 'ACTIVATE_POLL_FAILURE',
  CLOSE_POLL_START: 'CLOSE_POLL_START',
  CLOSE_POLL_SUCCESS: 'CLOSE_POLL_SUCCESS',
  CLOSE_POLL_FAILURE: 'CLOSE_POLL_FAILURE',
  FETCH_POLL_START: 'FETCH_POLL_START',
  FETCH_POLL_SUCCESS: 'FETCH_POLL_SUCCESS',
  FETCH_POLL_FAILURE: 'FETCH_POLL_FAILURE',
  FETCH_POLLS_START: 'FETCH_POLLS_START',
  FETCH_POLLS_SUCCESS: 'FETCH_POLLS_SUCCESS',
  FETCH_POLLS_FAILURE: 'FETCH_POLLS_FAILURE',
  CREATE_ANSWER_START: 'CREATE_ANSWER_START',
  CREATE_ANSWER_SUCCESS: 'CREATE_ANSWER_SUCCESS',
  CREATE_ANSWER_FAILURE: 'CREATE_ANSWER_FAILURE',
  CAST_VOTE_START: 'CAST_VOTE_START',
  CAST_VOTE_SUCCESS: 'CAST_VOTE_SUCCESS',
  CAST_VOTE_FAILURE: 'CAST_VOTE_FAILURE',
};

export default ActionTypes;
