const ActionTypes = {
  ACTIVATE_POLL_START: 'ACTIVATE_POLL_START',
  ACTIVATE_POLL_SUCCESS: 'ACTIVATE_POLL_SUCCESS',
  ACTIVATE_POLL_FAILURE: 'ACTIVATE_POLL_FAILURE',
  CLOSE_POLL_START: 'CLOSE_POLL_START',
  CLOSE_POLL_SUCCESS: 'CLOSE_POLL_SUCCESS',
  CLOSE_POLL_FAILURE: 'CLOSE_POLL_FAILURE',
};

export default ActionTypes;
